export {default as SlideShow} from './slideShow/SlideShow'
export {default as Food} from './food/Food'
export {default as Blog} from './blog/Blog'
export {default as Cart} from './cart/Cart'
export {default as Login} from './login/Login'
export {default as Register} from './register/Register'
export {default as ResetPassword} from './reset/ResetPass'